stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: |-
        mkdir -p /root/.m2 && mv settings.xml /root/.m2/
        mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar \
         -Dsonar.projectKey=test \
         -Dsonar.host.url=${SONA_HOST} \
         -Dsonar.login=${SONA_KEY}
    env:
      NEXUS_HOST: http://172.16.1.80:31231/
    envFrom:
    - sourceName: nexus-key
      sourceKey: admin
      targetKey: NEXUS_TOKEN
    - sourceName: sona-key
      sourceKey: host
      targetKey: SONA_HOST
    - sourceName: sona-key
      sourceKey: token
      targetKey: SONA_KEY
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 172.16.1.80:30928
    env:
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
